### ISSUE TITLE
Deploy safe transaction service (mainnet)

### ISSUE THREAD

**Issue by nicolasbrugneaux** [celo-org/safe-transaction-service#48]
- [x] staging
- [x] production

**Comment by alvarof2** [comment]
Deployed in [staging](https://console.cloud.google.com/kubernetes/clusters/details/us-west1-a/celo-safe-staging/details?project=clabs-gnosis-safe&supportedpurview=project) and [prod](https://console.cloud.google.com/kubernetes/clusters/details/us-central1/celo-safe-prod/details?project=clabs-gnosis-safe&supportedpurview=project), Helm release `celo-safe-tx-service-mainnet`.
