### ISSUE TITLE
Question: What is the Celo Safe base URL API?

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/safe-transaction-service#54]
_Copying a [question](https://forum.celo.org/t/multisig-celo-safe-re-launch/4529/23?u=0xarthurxyz) from the Celo Safe forum post for tracking purposes: **[[Multisig] Celo Safe (re)launch](https://forum.celo.org/t/multisig-celo-safe-re-launch/4529)**_

> Topic: API url base like Eth mainnet
> 
> Gnosis has this URL for the mainnet Safe:
> [https://safe-transaction-mainnet.safe.global/ 1](https://safe-transaction-mainnet.safe.global/)
> (! Note the different API endpoints compared to the Alfajores one below)
> 
> For Alfajores, I could only find this (by inspecting the network on the reforked Safe’s UI
> https://client-gateway.celo-safe-prod.celo-networks-dev.org/index.html
> (api base: `https://client-gateway.celo-safe-prod.celo-networks-dev.org`)
> 
> **Q**: Could you point me to the “correct” Alfajores API?
> For Celo would also be nice.
> More specifically, we need access to sth like
> 
> `POST /v1/safes/{address}/multisig-transactions/`
> `POST /v1/safes/{address}/multisig-transactions/estimations/`
> EDIT: After continuing playing around with the reforked Safe UI, I found this undocumented endpoint
> `POST /v2/chains/44787/safes/{safeId}/multisig-transactions/estimations`

**Comment by nicolasbrugneaux** [comment]
Replied here: https://forum.celo.org/t/multisig-celo-safe-re-launch/4529/35?u=nicolasbrugneaux

**Comment by arthurgousset** [comment]
Re-opening the issue with [response from owl_dev](https://forum.celo.org/t/multisig-celo-safe-re-launch/4529/37?u=0xarthurxyz) cc @nicolasbrugneaux:

> Hey there, ty for the answer.
> 
> What I’m missing with your link are requests like
> 
> More specifically, we need access to sth like
> 
> `POST /v1/safes/{address}/multisig-transactions/`
> `POST /v1/safes/{address}/multisig-transactions/estimations/`
> In my original post [[Multisig] Celo Safe (re)launch - #23 by owl_dev](https://forum.celo.org/t/multisig-celo-safe-re-launch/4529/23), I linked the Mainnet Gnosis Safe Swagger UI link, and they do have those endpoints.

**Comment by martinvol** [comment]
Replied again

**Comment by tamagosante** [comment]
> http://mainnet-tx-svc.celo-safe-prod.celo-networks-dev.org/
(Source: https://forum.celo.org/t/multisig-celo-safe-re-launch/4529/42?u=owl_dev)

> we haven’t configured statics yet

I haven't tested that URL yet, but I have a related question:
The url, looks like it is still in development.
How can I be sure, that it will not break over the days/weeks?

Or asked differently, where can I see the most up-to-date version of that URL?

@martinvol

**Comment by martinvol** [comment]
We plan to maintain that url going forward, the looks that url doesn't look "nice" it's because we set it up as an internal service, but will not change in the near future.
