### ISSUE TITLE
Feature Request: Custom Contract interaction missing (available in old/not in new)

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/safe-transaction-service#55]
Ref 1: _Copying [feedback from Nirvaan at Climate Collective](https://celo-org.slack.com/archives/C044C02AHAN/p1668803999326239) on Slack for better tracking_

> Few initial comments:
> - I don't see the "contract interaction" option any longer?
> - still facing an issue with the UI updating: i made this loom video https://www.loom.com/share/e0383e7b9cba4b0595887ba0af5afc7c to show what I mean and can screenshare live as well

Recording: https://www.loom.com/share/e0383e7b9cba4b0595887ba0af5afc7c

Ref 2: private feedback from cask.fi

> Hey, I saw the new safe version is now live. i noticed there is no 'contract interaction' option for a new transaction. is this on purpose? we use safe to manage our contract governance, perform upgrades, settings changes, etc, and we do all that via a contract interaction which is seems is no longer possible.

**Comment by nicolasbrugneaux** [comment]
I'm pulling and merging upstream in order to bring any new feature from the safe team. Maybe the contract interaction will be part of it.

**Comment by arthurgousset** [comment]
Added additional feedback on this in the ticket description:

> Ref 2: private feedback from cask.fi
> 
> > Hey, I saw the new safe version is now live. i noticed there is no 'contract interaction' option for a new transaction. is this on purpose? we use safe to manage our contract governance, perform upgrades, settings changes, etc, and we do all that via a contract interaction which is seems is no longer possible.

**Comment by fodisi** [comment]
Hi, Francis from GoodGhosting here.
Unfortunately I'm still facing this issue w/ the current website https://safe.celo.org/
<img width="958" alt="Screen Shot 2022-12-01 at 5 33 38 PM" src="https://user-images.githubusercontent.com/36540281/205173386-b3676629-ca8a-41c0-8e97-96ab1805366c.png">


However, using Gnosis Safe latest website version w/ Polygon, it does give the option to interact w/ the contract.

<img width="1296" alt="Screen Shot 2022-12-01 at 5 29 32 PM" src="https://user-images.githubusercontent.com/36540281/205173235-1d8ba9dd-b169-4949-80e3-dda8db96770b.png">

**Comment by vibern0** [comment]
Same as @fodisi. I need to use the contract interaction.
Previous version has it, but the new one doesn't.
![image](https://user-images.githubusercontent.com/19441097/206155020-bc4866c6-9420-42d3-b225-8a1355e2f448.png)
![image](https://user-images.githubusercontent.com/19441097/206155093-dae2ca7c-ad45-463b-aa42-69d427eae586.png)

**Comment by arthurgousset** [comment]
Thanks for the feedback @fodisi and @nicolasbrugneaux.

This is common feedback we heard!
Unfortunately this option seems to be have been removed by the Gnosis Safe team, which is why it is missing in the newer version of Celo Safe.

We'll share this feature request with them for their consideration.

**Comment by fodisi** [comment]
> Thanks for the feedback @fodisi and @nicolasbrugneaux.
> 
> This is common feedback we heard! Unfortunately this option seems to be have been removed by the Gnosis Safe team, which is why it is missing in the newer version of Celo Safe.
> 
> We'll share this feature request with them for their consideration.

Thanks for the help @0xarthurxyz .
Not sure if this additional piece of info is valuable, but the newest version of the official Gnosis Safe website (https://app.safe.global), which was also recently updated, does offer support for this feature.
Just sharing in case it's a config-related thing, or maybe some sort of add-on 🤔 

Thanks again for the all the support and help

**Comment by nicolasbrugneaux** [comment]
Thanks, that's very valuable information! We ran into issues compiling, when merging upstream into our fork, but that's good to know this feature will be pulled in whenever we fix that compile error :)

**Comment by nicolasbrugneaux** [comment]
Blocked by celo-org/web-core#6

**Comment by nicolasbrugneaux** [comment]
Unblocked. We published the merged upstream version and created a new `Transaction Builder` entry in the available apps.

![Image](https://user-images.githubusercontent.com/3650621/207078727-d27087a9-c1f0-4dad-bfb5-e6f8c58cea8e.png)

 It should look like that

**Comment by 0xarthurxyz** [comment]
@nicolasbrugneaux or @dckesler, could you also post the above screenshot and a short blurb on the Forum post. Thanks!

**Comment by 0xarthurxyz** [comment]
Shared an update on the forum 
![Uploading image.png…]()

**Comment by arthurgousset** [comment]
Shared an update on the forum 
<img width="771" alt="image" src="https://user-images.githubusercontent.com/46296830/207631776-f6886555-8427-437e-8d55-c0b71005f155.png">

**Comment by fodisi** [comment]
works like a charm @nicolasbrugneaux @0xarthurxyz . Thanks a lot 👏 👏 👏

**Comment by arthurgousset** [comment]
> works like a charm @nicolasbrugneaux @0xarthurxyz . Thanks a lot 👏 👏 👏

Great to hear!! Thanks for your feedback :)

**Comment by arthurgousset** [comment]
Closing this ticket because feature is live.
