### ISSUE TITLE
Bug: Caching (Indexing) issues

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/safe-transaction-service#56]
_Copying [issues reported on Forum post](https://forum.celo.org/t/multisig-celo-safe-re-launch/4529/27?u=0xarthurxyz) for better tracking in team_

> Hi [@richikchanda1999](https://forum.celo.org/u/richikchanda1999) and [@owl_dev](https://forum.celo.org/u/owl_dev) thanks both for reporting the indexing issue. Great catch!
> 
> Indeed, it looks like indexing is taking quite a while :thinking:
> This is not behaviour we observed in testing but we’re able to reproduce it on our end, so [@nicolasbrugneaux](https://forum.celo.org/u/nicolasbrugneaux) and [@martinvol](https://forum.celo.org/u/martinvol) are looking into this right now!

[Ref 1](https://forum.celo.org/t/multisig-celo-safe-re-launch/4529/26): 
> I tried to execute a transaction from my safe (0x73d2231a223e46864d9B35FEC712160c3A3AaBd6) on Celo Mainnet. It is stuck at indexing on https://safe.celo.org/ after the new update right now.
> The safe transaction hash is 0x1d1eda2aa70be002061a41f60c21765cfbaebf8415b9ed68b0aadb5a3cadb11b
> 
> I have added a screenshot here - [Screenshot 2022-11-16 at 6.20.38 PM.png - Google Drive](https://drive.google.com/file/d/1Qf_0yN_NFvS120DwLYGvFMMIMnStLW4A/view?usp=sharing)

[Ref 2](https://forum.celo.org/t/multisig-celo-safe-re-launch/4529/24): 

> Topic: Long indexing times?
> 
> I had 2 tx
> 
> one took ~10min to index
> the other is still indexing at ~20+ min now

Ref 3: 
Copying [feedback from Nirvaan at Climate Collective](https://celo-org.slack.com/archives/C044C02AHAN/p1668803999326239) on Slack for better tracking

> Few initial comments:
> 
> [...]
> still facing an issue with the UI updating: i made this loom video https://www.loom.com/share/e0383e7b9cba4b0595887ba0af5afc7c to show what I mean and can screenshare live as well
> 
1. Initiating a transaction here:
![image](https://user-images.githubusercontent.com/46296830/203615166-db521376-5b4b-4f67-a5de-2c800b1d0389.png)

2. Transaction appears in old UI but doesn't appear on new UI
![image](https://user-images.githubusercontent.com/46296830/203615138-b00238cb-57ba-4f1c-b90f-8e6277d4da51.png)

![image](https://user-images.githubusercontent.com/46296830/203615156-30c375f4-ef8b-4901-8f80-8879bd64a53c.png)

**Comment by nicolasbrugneaux** [comment]
Deployed on staging via (celo-org/infrastructure#566 and testing if it works well. Production awaiting here: celo-org/infrastructure#562)

**Comment by arthurgousset** [comment]
Updated the ticket description with additional feedback from Nirvaan. 

Ref 3: 
Copying [feedback from Nirvaan at Climate Collective](https://celo-org.slack.com/archives/C044C02AHAN/p1668803999326239) on Slack for better tracking

> Few initial comments:
> 
> [...]
> still facing an issue with the UI updating: i made this loom video https://www.loom.com/share/e0383e7b9cba4b0595887ba0af5afc7c to show what I mean and can screenshare live as well
> 
1. Initiating a transaction here:
![image](https://user-images.githubusercontent.com/46296830/203615166-db521376-5b4b-4f67-a5de-2c800b1d0389.png)

2. Transaction appears in old UI but doesn't appear on new UI
![image](https://user-images.githubusercontent.com/46296830/203615138-b00238cb-57ba-4f1c-b90f-8e6277d4da51.png)

![image](https://user-images.githubusercontent.com/46296830/203615156-30c375f4-ef8b-4901-8f80-8879bd64a53c.png)

**Comment by nicolasbrugneaux** [comment]
This seems fixed :) We updated the environment configs to clear the caches of the gateway-client properly.
